### ISSUE TITLE
大佬好，求一份项目的docker镜像文件

### ISSUE THREAD

**Issue by AmusingOurselves** [quzhi1/ChineseHistoricalSource#8]
大佬好，在知乎看见了您对这个项目的介绍，自己尝试了按照教程安装，但是有各种问题，百般无奈下，想要一份大佬已经运行好的docker镜像文件

**Comment by quzhi1** [comment]
你是要Dockerfile吗？这个项目需要ElasticSearch和Kibana两个container。可以用这个：https://github.com/quzhi1/ChineseHistoricalSource/blob/master/docker-compose.yml

**Comment by shaowei1** [comment]
万般无奈之下, 我仿照写了一个python的，运行简单 https://github.com/shaowei1/HistoricalLibrary

**Comment by quzhi1** [comment]
没问题。这个项目很长时间不maintain了，可能有些东西不work。哪天我搞个Helm chart应该会好得多。
