### ISSUE TITLE
uninitialized constant Elasticsearch::Transport (NameError)

### ISSUE THREAD

**Issue by Suacrbah** [quzhi1/ChineseHistoricalSource#9]
您好，我在ubuntu 20.04环境下运行ruby `ruby/es_feeder.rb`命令时，发生错误，说Elasticsearch::Transport未初始化，但我刚接触ruby，并不知道应该如何初始化该变量。

![Screenshot from 2022-04-08 01-31-03](https://user-images.githubusercontent.com/39693399/162264110-a3e93d69-d464-4ff6-828c-cd048e961673.png)

经过搜索发现可能是没有装elasticsearch-transport的gem，但是安装后依旧无法运行。在配置环境的时候因为ruby版本问题我将sorbet升级到了最新版，不知道是不是因为这个原因，如果是的话麻烦大佬透露一下兼容的ruby版本，我试了好几个版本都没有办法运行，感谢！

**Comment by shaowei1** [comment]
我也不会ruby, 我仿照写了一个python的，运行简单 https://github.com/shaowei1/HistoricalLibrary

**Comment by Suacrbah** [comment]
> 我也不会ruby, 我仿照写了一个python的，运行简单 https://github.com/shaowei1/HistoricalLibrary

非常感谢，已经运行好了
